name: persian_horizontal_date_picker
description: A customizable horizontal date picker library for Flutter. Support both jalali and gregorian dates.
version: 0.1.0
repository: https://github.com/ariaramin/persian_horizontal_date_picker

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1
  shamsi_date: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
        
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf